### ISSUE TITLE
aligned or unaligned bam files? 

### ISSUE THREAD

**Issue by nnneeennn** [epi2me-labs/wf-somatic-variation#10]
### Ask away!

Hi,

in your quickstart you mention that this pipeline works only with aligned bams, however the nextflow_schema.json asks for aligned or unaligned bam files for both tumor and normal bams. This is also the info you get when running `nextflow run epi2me-labs/wf-somatic-variation --help `. 

I have previously started this workflow from unaligned bam files and did not get an error, now I am wondering whether I need to rerun from aligned bams instead? 

Thank you, 
Nina

**Comment by TBradley27** [comment]
Just to add to this, I was able to also run the pipeline from unaligned bams, which seemed to run successfully

The reason I used unaligned bams, is that, at this point I am not sure how to use an aligner such as minimap2 and to preserve base modification information

**Comment by RenzoTale88** [comment]
Hi @nnneeennn, @TBradley27 yes, the workflow accepts both aligned and unaligned BAM (uBAM) files. Providing an unaligned/aligned to a different reference BAM will cause the workflow will automatically perform a mapping of the sequences prior to downstream analyses.

@TBradley27 just to reassure you, when working with an uBAM file the workflow will preserve the details of the modified bases in the MM/ML fields used for the downstream tools. You can see how we remap the sequences with minimap2 [here](https://github.com/epi2me-labs/wf-somatic-variation/blob/master/modules/local/common.nf#L68-L69).

I hope this helps.
Andrea

**Comment by nnneeennn** [comment]
should your readme be updated to reflect this?

**Comment by RenzoTale88** [comment]
There will be an extensive update of the README in the next release.
