### ISSUE TITLE
error trying to run on HPC

### ISSUE THREAD

**Issue by Jane-Gibson** [epi2me-labs/wf-somatic-variation#14]
### Operating System

Other Linux (please specify below)

### Other Linux

redhat

### Workflow Version

v.1.1.0

### Workflow Execution

Command line

### CLI command run

#run test data
${nextflow_exe_path} run epi2me-labs/wf-somatic-variation \
--bam_normal wf-somatic-variation-demo/demo_normal.bam \
--bam_tumor wf-somatic-variation-demo/demo_tumor.bam \
--ref wf-somatic-variation-demo/GCA_000001405.15_GRCh38_no_alt_analysis_set_chr20.fna \
--sv \
--snv \
--mod \
--sample_name SAMPLE \
--normal_min_coverage 0 \
--tumor_min_coverage 0 \
-profile apptainer \

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

I'm running the somatic nextflow workflow via apptainer (singularity) on our HPC. 
It is failing at bam_ingress_normal:minimap2_ubam due to Relocation not allowed with starter-suid.

Is there a way to change our apptainer set up to allow this?  or some option I should enable? thanks.

### Relevant log output

```shell
ERROR ~ Error executing process > 'bam_ingress_normal:minimap2_ubam (1)'

Caused by:
  Process `bam_ingress_normal:minimap2_ubam (1)` terminated with an error exit status (255)

Command executed:

  samtools bam2fq -@ 1 -T 1  demo_normal.bam | minimap2 -y -t 1 -ax map-ont GCA_000001405.15_GRCh38_no_alt_analysis_set_chr20.fna -     | samtools sort -@ 1 --write-index -o SAMPLE.cram##idx##SAMPLE.cram.crai -O CRAM --reference GCA_000001405.15_GRCh38_no_alt_analysis_set_chr20.fna -

Command exit status:
  255

Command output:
  (empty)

Command error:
  FATAL:   Relocation not allowed with starter-suid

Work dir:
  /mainfs/scratch/jg/ONT_ANALYSES/NEXTFLOW/SOMATIC/work/7d/492f230af0c36d8f0ce2d7972b09d5

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by SamStudio8** [comment]
Hi @Jane-Gibson, rather fortuitously another user reported a similar issue yesterday: https://github.com/epi2me-labs/wf-human-variation/issues/161. It appeared to be related to how data partitions are mounted on particular clusters. I would have a chat with your HPC administrator about this error in the first instance as they should hopefully be able to advise on the specifics of your HPC better than we can.

**Comment by Jane-Gibson** [comment]
ok, thanks. I will ask them and point them to the other issue.
