### ISSUE TITLE
Multiple inputs/design for mod

### ISSUE THREAD

**Issue by umranyaman** [epi2me-labs/wf-somatic-variation#15]
### Ask away!

Hello,

Sorry if I missed, I was wondering whether we can input multiple samples? 

For multi factor experiments, it would be great if we could perform methylation analysis based on these design. Currently have to do the dmr analysis locally due to the experimental design. 

Thanks,
Umran

**Comment by RenzoTale88** [comment]
Hello @umranyaman, at this stage the workflow support a single pair of tumor/normal individuals.
