### ISSUE TITLE
error exit code 1

### ISSUE THREAD

**Issue by selmapichot** [epi2me-labs/wf-somatic-variation#19]
### Ask away!

Hi, 
I had this error message after running this workflow with unaligned tumour/normal bam files with the GRCh38 as reference genome:
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'snv:concat_bams (1)'

Caused by:
  Process `snv:concat_bams (1)` terminated with an error exit status (1)

Any advice on how to sort this issue ? Many thanks.
All the best,
Selma.

**Comment by RenzoTale88** [comment]
Hi @selmapichot please re-open this as a Bug Report. The page will ask you a number of pieces of information that are useful for us to be able to help you.
