### ISSUE TITLE
SNP: low quality score filtering

### ISSUE THREAD

**Issue by selmapichot** [epi2me-labs/wf-somatic-variation#20]
### Ask away!

Hi,
when running the workflow for SNP, is it possible to set a threshold for clairS to filter out low quality variants ?
Many thanks,
Selma.

**Comment by RenzoTale88** [comment]
Hi @selmapichot you can apply a soft filter on the QUAL value with the `--min_qual` option. The default value is currently set to 8.
Please note that the variants are soft-filtered, meaning that the site will be in the VCF file, but with a `FILTER` tag set.

**Comment by selmapichot** [comment]
Many thanks for your reply. I noticed that all variants are reported in the final snp html report, even the LowQual ones that are below the threshold of 8. So I was wondering if the workflow could generate a "cleaner" html report by filtering out the LowQual variants.
