### ISSUE TITLE
Add chosen basecaller model into the main.nf error

### ISSUE THREAD

**Issue by lucy924** [epi2me-labs/wf-somatic-variation#30]
### Is your feature related to a problem?

It's related to the basecaller model checks for ClairS

### Describe the solution you'd like

The error output on line 486 of main.nf (v1.3.0-g5bb2ee4) could you add the basecaller_cfg it's looking at please? I spent ages thinking I'd used a basecaller that was supported by ClairS when I finally edited the error output myself to get that info and found out it was a different one, and that's why it wasn't working.

### Describe alternatives you've considered

N/A

**Comment by RenzoTale88** [comment]
Hi @lucy924 thank you for your suggestion, I will open a ticket to address this.

**Comment by RenzoTale88** [comment]
@lucy924 we expanded on the error logging to provide a more informative error message.

Andrea
