### ISSUE TITLE
Enable overriding basecaller model when multiple different basecallers are found in the BAM headers

### ISSUE THREAD

**Issue by sabackman** [epi2me-labs/wf-somatic-variation#32]
### Is your feature related to a problem?

I'm currently running this pipeline on a set of tumor-normal samples generated at an external sequencing facility. For reasons currently unknown to me some of my samples have strings like "dna_r10.4.1_e8.2_400bps_sup@v4.2.0-363DBFF3" (where the final hexadecimal number varies even within samples) rather than just "dna_r10.4.1_e8.2_400bps_sup@v4.2.0" in the readgroup IDs. I'm confident that they are all basecalled with the standard dna_r10.4.1_e8.2_400bps_sup@v4.2.0 model. 

This causes the pipeline to output an error message about finding different variant callers and abort, and it is not possible to override the behaviour.

### Describe the solution you'd like

I'd like to be able to override this behaviour, just like for cases when no basecaller model is detected. I'm currently making minor modifications myself (just adding an if-else clause like for the case where no models are found) to be able to run my samples. 

### Describe alternatives you've considered

At least in the case of my samples the header contains the string "basecall_model=dna_r10.4.1_e8.2_400bps_sup@v4.2.0" in addition to the read group ID (from which it appears the pipeline is inferring the basecaller model?) - an alternative could perhaps be to alter the manner in which basecaller models are inferred.

**Comment by RenzoTale88** [comment]
@sabackman that was a know issue that should be fixed as of v1.3.1. Can you update the workflow and let us know if this fixes it? 
Ensure to drop the previous version before pulling the workflow again:
```
nextflow drop epi2me-labs/wf-somatic-variation
nextflow run epi2me-labs/wf-somatic-variation ...
```

**Comment by sabackman** [comment]
Hi! I have updated to v 1.3.1, which I realise was not clear from my description. I'm running on a secure compute cluster with no direct internet access so I've downloaded the source tar.gz file and built the singularity images and transferred them there separately. 

Looking at the main.nf file (lines 427-443) it seems that if >1 model is found, it doesn't matter if the override_basecaller_cfg option is used, error message will be posted and the execution halted.

**Comment by RenzoTale88** [comment]
Indeed, if the workflow finds multiple basecall models it fails. This is an expected behaviour, as data basecalled with different models will have different characteristics, and should not be mixed.
Having said that, it is curious that the workflow is finding multiple models based on the suffix. This should've be fixed in the current release of the workflow. 
Could you please open a new issue reporting a bug, instead of a feature request? That will ask you more questions on how you ran the analysis and will help us understand what went wrong.

Andrea
