### ISSUE TITLE
bamstats error

### ISSUE THREAD

**Issue by flokraft85** [epi2me-labs/wf-somatic-variation#38]
### Operating System

Ubuntu 22.04

### Workflow Version

1.3.0

### Workflow Execution

Command line (Local)

### CLI command run

sudo nextflow run epi2me-labs/wf-somatic-variation --snv --sv --mod --tr_bed /data/ref/human_GRCh38_no_alt_analysis_set.trf.bed --sample_name 'test' --ref /data/ref/GRCh38_no_alt_analysis_set_dup_masked.fa --bam_normal test_normal.bam --bam_tumor test_tumor.bam --out_dir /test --normal_min_coverage 0 --tumor_min_coverage 0 --germline true --phase_normal true --liquid_tumor true --ubam_map_threads 32 --ubam_sort_threads 27 --severus_threads 32 --dss_threads 4 --modkit_threads 20 --haplotype_filter_threads 20 -profile standard -w /data/work/

### Workflow Execution - CLI Execution Profile

None

### What happened?

Hi,
unfortunately running wf-somatic-variation fails, due to bamstats. The normal bam has a high number of reads, due to the strong fragmentation of the sample (~80mio reads). Maybe this could be an problem? Is there any possibility to skip bam stats or to fix this issue. 
Thanks in advance.
Best,
Florian

### Relevant log output

```shell
ERROR ~ Error executing process > 'alignment_stats:bamstats (1)'

Caused by:
  Process `alignment_stats:bamstats (1)` terminated with an error exit status (137)


Command executed:

  bamstats reads.bam \
      -s test \
      --threads 3 \
      -i "test_normal.normal.per-file-runids.txt" \
      -l "test_normal.normal.basecallers.tsv" \
      -u \
      --histograms hists_test_normal_normal \
      -f tet_normal_normal.flagstat.tsv \
      | gzip > "test_normal_normal.readstats.tsv.gz"
  
  # get unique run IDs
  awk -F '\t' '
      NR==1 {for (i=1; i<=NF; i++) {ix[$i] = i}}
      # only print run_id if present
      NR>1 && $ix["run_id"] != "" {print $ix["run_id"]}
  ' test_normal.normal.per-file-runids.txt | sort | uniq > test_normal.normal.runids.txt
  # get unique basecall models
  awk -F '\t' '
      NR==1 {for (i=1; i<=NF; i++) {ix[$i] = i}}
      # only print basecall model if present
      NR>1 && $ix["basecaller"] != "" {print $ix["basecaller"]}
  ' 24-1049LR.normal.basecallers.tsv | sort | uniq > 24-1049LR.normal.basecallers.txt

Command exit status:
  137

Command output:
  (empty)

Command error:
  .command.sh: line 10:    30 Killed                  bamstats reads.bam -s 24-1049LR --threads 3 -i "24-1049LR.normal.per-file-runids.txt" -l "24-1049LR.normal.basecallers.tsv" -u --histograms hists_24-1049LR_normal -f 24-1049LR_normal.flagstat.tsv
          32 Done                    | gzip > "24-1049LR_normal.readstats.tsv.gz"

Work dir:
  /data/work/0d/d97a217902f4bef5d20ab65e79245d

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by nrhorner** [comment]
Hi @flokraft85 

I don't think there is a way to skip the bamstats step.

You could try increasing the memory allocated to this process

create a file with the following contents called memory.config (for example)
```
process {
	 withName: bamstats {
		memory = 16.GB
	 }
 }
```
Run your workflow with the following additions to the command. The (-resume allows the report to be made without running the whole workflow again).
 -c memory.config -r resume

**Comment by flokraft85** [comment]
Hi @nrhorner,
thanks for the suggested workaround.
I tried in between to increase the memory allocation for the step and this solve the issue. However, I was a little lazy and did not want to do different iterations, so I increase the memory to 128GB for the step.
I also had memory issues with other processes in the wf-somatic-variation run. 
Please find a list below. Maybe there is another way to fix the memory issues in general, without adjusting this for every processes.
- get_qual_filter
- aggregate_all_variants
- severus
- pileup_variants
- evaluate_candidates

Thanks again for your support.

Best,
Florian

**Comment by SamStudio8** [comment]
Thanks @flokraft85 - we're slowly improving our handling of memory in these processes across humvar and somvar. I'm closing this now but please do open issues in future if you're still having these troubles on newer versions.
