### ISSUE TITLE
non-human reference genomes

### ISSUE THREAD

**Issue by ChristopherRichie** [epi2me-labs/wf-somatic-variation#4]
### Ask away!

Can this wf be used with other species reference genomes? (mouse, rat, etc)?

the "FRONT PAGE" says :

> The workflow relies on three primary input files:
> 
> A reference genome in [fasta format](https://www.ncbi.nlm.nih.gov/genbank/fastaformat/)
> An [aligned BAM file](https://samtools.github.io/hts-specs/SAMv1.pdf) for the tumor sample
> An [aligned BAM file](https://samtools.github.io/hts-specs/SAMv1.pdf) for the normal sample
> The reference genome should be either hg19 (GRCh37) or hg38 (GRCh38). 

Why are hg19/hg38 suggested here?  (is it species-related or formatting-related, etc?)

thanks

**Comment by RenzoTale88** [comment]
Hi @ChristopherRichie currently the workflow is designed to work only with these two genome build (hg19 and hg38).
We are working on making the component that do not rely on the genome information accessible regardless of the input genome.

**Comment by RenzoTale88** [comment]
@ChristopherRichie workflow v0.4.0 should be able to run on any species, provided you set `--annotation false --classify_insert false`. Please let me know if you come across any issue with it.
Andrea

**Comment by ChristopherRichie** [comment]
THANKS.  i will give it a try.
