### ISSUE TITLE
Can input be CRAM

### ISSUE THREAD

**Issue by kiranpatil222** [epi2me-labs/wf-somatic-variation#6]
### Ask away!

Hi, 

Does this Wf take CRAM input , as i wanted to try pipeline woth your ONT aws data, i see CRAM files are available,

Which folder files should one download from the below for Tumor/normal as Pair for analysis

```
 aws s3 ls --no-sign-request s3://ont-open-data/colo829_2023.04/COLO829/
                           PRE PAK76302/
                           PRE PAO29420/
                           PRE PAO32033/
aws s3 ls --no-sign-request s3://ont-open-data/colo829_2023.04/COLO829BL/
                           PRE PAK76487/
                           PRE PAO33946/
```

**Comment by RenzoTale88** [comment]
Hi @kiranpatil222 the workflow should accept CRAM as an input.
The cells used in the blog post are the ones named `PAOXXXXX`. Keep in mind that the workflow accepts one input bam/cram for tumor and one for normal, and you need to combine multiple cram/bam for the same sample beforehand.
